#!/bin/sh

trap 'exit 0' SIGINT SIGTERM

DNS_TTL=${DNS_TTL:-150}

while :; do

   NIP=`dig +short myip.opendns.com @resolver1.opendns.com`

   if [ $? -eq 0 -a "$IP" != "$NIP" ]; then

      echo "Changing from '$IP' to '$NIP'"
      unset VALUES

      for NAME in $DNS_RECORDS; do
         VAL=`printf '{ "Action":"UPSERT", "ResourceRecordSet":{ "ResourceRecords":[ { "Value":"%s" } ], "Name":"%s", "Type":"A", "TTL":%s }}' "$NIP" "$NAME" "$DNS_TTL"`
         VALUES="$VALUES${VALUES+,}$VAL"
      done

      JSON=`printf '{ "ChangeBatch": { "Comment":"Auto updating @ %s", "Changes":[ %s ] }}' "$(date)" "$VALUES"`

      aws route53 change-resource-record-sets --hosted-zone-id $AWS_HOSTED_ZONE_ID --cli-input-json "$JSON" &&
         IP="$NIP"
   fi

   sleep 5
done
