name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        echo ${{ secrets.TOKEN }} | docker login --username gllera --password-stdin
        docker build --tag gllera/rsss .
        docker push gllera/rsss
